### ISSUE TITLE
BUG: Action type "page Navigation" not picking up pages created in .pbip file

### ISSUE THREAD

**Issue by efeeed-go-home** [PowerBI-tips/tools#42]
I've created a wireframe project that has a number of different pages with various layouts.  Once opened in Power BI Desktop I want to add a blank button on top of the company logo (top left) that, when clicked, returns the user to the homepage of the report.  

Unfortunately, none of the pages created whilst wireframing are detected when selecting the Action type "page navigation".  

- I"ve attempted to save the file as a .pbix and tried again this does not seem to help
- Only subsequent pages created once the file has been opened are actually picked up and displayed as a navigatable option
- adding the page navigator visual works (i.e. pages are detected) however navigation to those pages once the visual is on the page does not work with the following error "Unable to navigate to destination - This page may not exist or may not be a valid destination"

Apologies if I've missed something completely obvious all help is appreciated!

**Comment by MikeCarlo** [comment]
great description, I've been able to replicate the issue.

I think this is due to a change in the Microsoft Spec for PBIP formats. Since this feature is currently in preview there are still some changes happening. 

We have opened an issue #51 that will address this issue by updating our format to the current format of PBIP
