### ISSUE TITLE
Purchased license but still no access

### ISSUE THREAD

**Issue by lunndal** [PowerBI-tips/tools#46]
On the 21. Of June I paid for a subscription at powerbi.tips. I authenticated using my GitHub account, "lunnal". When I am logged in and view my subscription it still requires me to pay.

Is the subscription service broken?

How would I go about using my aquired subscription?

Best,
Terje

**Comment by MikeCarlo** [comment]
I can see you have logged into a Microsoft account and a Github account.  Try logging into the site using a private browser with your Github account login.  

likely since we use Microsoft active directory it is auto logging you in using your Microsoft account. 

We see this often when users pay for the subscription with one account but log in with a different identity provider.

**Comment by PBetzel** [comment]
I have the same issue. But logged in only with Microsoft account?
